### ISSUE TITLE
receive lost data

### ISSUE THREAD

**Issue by JerryZheng89** [mac-can/PCBUSB-Library#13]
- Device:  PCAN FD
- Host:  Macbook Pro M1 14
- Source Code: pcbusb_recv.cpp
- clang version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
- Baudrate: PCAN_BAUD_500K
- library version: 0.11.2

1. when I send small amount  can datas, for example send 10 can packages every 1 second,  **pcbusb_recv** will never receive the can data.

2. But when I send massive can data, which is can bus log file, on the bus, the **pcbusb_recv** will receive some data package of the can bus and massive data will not be received!

3. I install ubuntu virtual machine in Parallels, the **pcan fd** device works ok in it!

4. The lost data on receiver cannot be  acceptable~~

**Comment by mac-can** [comment]
Not reproducible.

@JerryZheng89 Can you please provide the traffic generator code and your modifications to `pcan_rcv.cpp`. Also which PCAN device you use and its firmware version number would be helpful.

**Comment by mac-can** [comment]
Issue closed. No additional information given. No confirmation by other users.
