### ISSUE TITLE
PCAN Multiple Application Access

### ISSUE THREAD

**Issue by InfallibleProgrammer** [mac-can/PCBUSB-Library#15]
Allowing the MAC CAN driver to send data to multiple applications that are using the PCAN dongle? Is this possible, if so, how many I do it?

The goal is to use 1 PCAN dongle but access it using multiple python scripts that are running at the same time.

**Comment by mac-can** [comment]
Sorry for answering late, but shared access to PCAN devices is not planned for the project (It`s not a SocketCAN driver).
