### ISSUE TITLE
Not working on Monterey

### ISSUE THREAD

**Issue by mauriciofarina** [mac-can/PCBUSB-Library#4]
Hello!

After upgrading my Mac to Monterey I lost access to my device. When Running the Python Example I receive the error:
`Error: (0, b'The driver is not loaded')`

The Mac still recognizes the PCAN-USB device and shows it on system report menu

```
PCAN-USB:

  Product ID:	0x000c
  Vendor ID:	0x0c72
  Version:	54.ff
  Speed:	Up to 12 Mb/s
  Manufacturer:	PEAK-System Technik GmbH
  Location ID:	0x14222000 / 9
  Current Available (mA):	500
  Current Required (mA):	200
  Extra Operating Current (mA):	0
```

I tried searching on how to reload Mac drivers and things like that, but I have no experience on Mac drivers, kernel....

**Comment by mac-can** [comment]
Hey guys,
can you try to compile and run the PCBUSB Monitor App. It also loads the PCBUSB dylib at run-time.
Just to make sure it is not a Python issue on Monterey.

**Comment by mauriciofarina** [comment]
I also thought this could be the issue. However, I tried installing anaconda and running with different python releases and the problem persisted. So I don't think this is the problem...
Anyway, I'll try the Monitor App and I'll let you know

**Comment by mac-can** [comment]
@mauriciofarina A while ago I´ve patched the PCANBasic.py from Peak-System after I ran into problems with Python 2.7 on macOS (10.13 and 11.x). Maybe you can try out this patch: [PCANBasic.zip](https://github.com/mac-can/PCBUSB-Library/files/7470659/PCANBasic.zip)
See also my Gist [macOS Library for PCAN-USB Interfaces: Python Example](https://gist.github.com/mac-can/55fd0f2ebc316116f553f1d327d68dd6)

**Comment by mauriciofarina** [comment]
@mac-can I tried using the patch you provided and compiling the PCBUSB Monitor App (V0.3) and, in both cases, the problem persists.

The error is always the same (No driver Loaded)...

Here's a screenshot of the Monitor App Screen and Xcode Logs:
![Screen Shot 2021-11-06 at 12 57 09](https://user-images.githubusercontent.com/11233122/140615918-a53d691b-a791-4186-bf0b-42a6a3fe66a9.png)

**Comment by mac-can** [comment]
hmm, ...

The library is compiled with the old Eclipse build environment; no target system is set, so it still runs under macOS 10.x.
Maybe that this is denied by macOS 12.x and reveals the error message.

A preliminary version of the [PCBUSB dylib](http://www.uv-software.de/files/downloads/MacCAN/PCANUSB/Library/OS_X_Library_for_PCANUSB_v0.10.ub.tar.gz) compiled as Universal macOS Binary can be downloaded here:
https://www.uv-software.de/dokuwiki/doku.php?id=uvs:programs:pcbusb_library
It should run on Intel and ARM architectures, but it is not tested on arm64.
And a colleague has confirmed that it is running on Monterey.

Happy CANgineering.

**Comment by mauriciofarina** [comment]
Hello @mac-can !

Just tried the preliminary version and it work perfectly!

Thank you for the help!

**Comment by taraskarpuk** [comment]
python3 pcbusb_recv.py               
Error: (0, b'The driver is not loaded')
Same Issue on Monterey :(

Well, seems it work once ... 

`ls -la /usr/local/lib/libPC*                                                                                                            ✔
-rwxr-xr-x@ 1 flow  admin  151496 May  6  2021 /usr/local/lib/libPCBUSB.0.10.dylib
-rwxr-xr-x@ 1 flow  admin  401616 Feb  7 12:57 /usr/local/lib/libPCBUSB.0.11.dylib
lrwxr-xr-x  1 flow  admin      35 Feb  7 12:57 /usr/local/lib/libPCBUSB.dylib -> /usr/local/lib/libPCBUSB.0.11.dylib`

Tried different versions ... and nothing. Intel x64 platform

**Comment by taraskarpuk** [comment]
@mauriciofarina What does preliminary version mean?  i have tried 0.11 version

**Comment by mauriciofarina** [comment]
@taraskarpuk the preliminary version is the `OS_X_Library_for_PCANUSB_v0.10.ub.tar` file. Try using it and see if it works for you. That was the solution for me!

**Comment by taraskarpuk** [comment]
Ok! Now it's working with "MacCan Monitor"... But i use python-can library... And seems i have problem with sending messages. Transmits only ID and DLC=0 and No data transmitted

**Comment by taraskarpuk** [comment]
https://github.com/hardbyte/python-can/issues/1117
