### ISSUE TITLE
MacOS Monterey library issue

### ISSUE THREAD

**Issue by daniInfi7** [mac-can/PCBUSB-Library#6]
Dear,
I have successfully used the driver before on macOS Big Sur, but now after upgrading the system (fresh install) the driver stopped working. My code is written in python but I have also tested the MacCAN Monitor, both without success.

Further details:
CPU: Intel
macOS: 12.2.1
hardware: PCAN-USB adapter

python output: "The driver is not loaded"
MacCAN Monitor output: "Something went terribly wrong! Error 0200: The driver is not loaded"

I tried the universal_64 and Intel_x86_64 0.10.1 and 0.11 version. The result is always the same.

**Comment by daniInfi7** [comment]
As you have suggested I have checked the issue #4 and the solution was to use the binary `macOS_Library_for_PCANUSB_v0.10.1.tar.gz` from https://www.uv-software.de/dokuwiki/doku.php?id=uvs:programs:pcbusb_library

is there any difference with this binary and the one that is included in the Library folder inside `MacCAN_Monitor.0.4_x86.1.dmg`?

**Comment by mac-can** [comment]
As stated in my [comment of 11/10/21](https://github.com/mac-can/PCBUSB-Library/issues/4#issuecomment-965667435), the x86_64 version is compiled to run on old OS X versions (tested with 10.13).
Maybe this is denied by Monterey. No further differences.

@daniInfi7 What´s about PCBUSB-Library version 0.11 (universal binary) is it running on you Mac now?

**Comment by daniInfi7** [comment]
@mac-can I have now tested different scenarios and the  0.11 (universal binary) as also 0.10.1 (included in the .dmg) work only with the c++ example and test/monitor example, with mac-can app and python they don't. 

macOS_Library_for_PCANUSB_v0.10.1.tar.gz works with everything.

**Comment by mac-can** [comment]
Issue reopened because it is not solved for v0.11 of the library on Monterey.

I was able to reproduce the error on a system with Monterey (12.1):
- The [C++ examples](https://github.com/mac-can/PCBUSB-Library/tree/main/Examples/C%2B%2B), which load the library at compile time, work fine.
- The [Python example](https://github.com/mac-can/PCBUSB-Library/tree/main/Examples/Python), which loads the library at runtime, throws the error code 512 ("The driver is not loaded").
- The [MacCAN Monitor App](https://github.com/mac-can/PCBUSB-Monitor) does the same.

Further investigations required.

**Comment by kedvall** [comment]
Hi @mac-can @daniInfi7. I'm currently experiencing the exact same issue. Any updates?
- I'm on Monterey 12.3
- I'm trying to use the v0.11 universal binary release on Python 3.9
- I can't use anything that loads the library at runtime, also throws the 512 (driver is not loaded) error
I would be happy to help debugging but I'm not really sure where to start

**Comment by mac-can** [comment]
> Hi @mac-can @daniInfi7. I'm currently experiencing the exact same issue. Any updates?
> 
> * I'm on Monterey 12.3
> * I'm trying to use the v0.11 universal binary release on Python 3.9
> * I can't use anything that loads the library at runtime, also throws the 512 (driver is not loaded) error
>   I would be happy to help debugging but I'm not really sure where to start

Hi @kedvall,
Occasionally, I get this [crash report](https://github.com/mac-can/PCBUSB-Monitor/files/8352782/crashreport.txt) when I try to connect to a PCAN interface in the [MacCAN Monitor App](https://github.com/mac-can/PCBUSB-Monitor) while using PCBUSB-Library version 0.11 on macOS Monterey (arm64). (I have never seen this behavior on Big Sur (x86_64) nor on High Sierra.)
I can't figure it out, but maybe it's a starting point for root causing or debugging.

**Comment by herrspade** [comment]
Hi, I have the same problem.

- Monterey 12.3.1 (21E258)
- Intel Core i7
- Python 3.10.2 (pyenv)
- can_moni works
- building and running pcbusb_recv and pcbusb_send examples work
- Everything python seems to fail with status 0x200 'The driver is not loaded'

Anything I can do to assist finding/fixing the problem?

**Comment by Dan-Kouba** [comment]
I am seeing the same "The driver is not loaded" issue on my machine:
- Monterrey 12.2.1
- Intel Core i9
- Python 3.8
- Both python-can v4.0.0 and MacCAN fail with the same error

**Comment by mac-can** [comment]
Preliminary version that should solve the issue: [macOS_Library_for_PCANUSB_v0.11.1.pre.tar.gz](https://github.com/mac-can/PCBUSB-Library/files/8566791/macOS_Library_for_PCANUSB_v0.11.1.pre.tar.gz)

**Comment by herrspade** [comment]
Great work, tested it and It works from me!

**Comment by Dan-Kouba** [comment]
This works for me as well, thank you!

**Comment by mac-can** [comment]
Bug fix release [v0.11.1](https://github.com/mac-can/PCBUSB-Library/releases/tag/v0.11.1) available. Issue can be closed
